<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$stat_img = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/upload1.png";
$loadig_gif = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/loader-1.gif";
$baseURL = $storeManager->getStore()->getBaseUrl();
$bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
$add_work = "";
if ($block->getCustomer()->getCustomAttribute('add_work')) {
    $add_work = $block->getCustomer()->getCustomAttribute('add_work')->getValue();
}
if ($add_work == "") {
    $av = 1;
} else {
    $av = 2;
}
//echo $av;
?>
<script type="text/javascript">
    var defaultImage = "<?php echo $stat_img; ?>",
            baseUrl = "<?php echo $storeManager->getStore()->getBaseUrl(); ?>";
    require(["jquery"], function ($)
    {
    $(document).ready(function ()
    {
    $('#loading').hide();
    });
    });
    function remove_art(){
    var r = confirm("Are sure you want to delete!");
    if (r == true) {
    jQuery(".field.add_work").show();
    jQuery("#upld_img").attr("src", defaultImage);
    jQuery(".art-remove-action").hide();
    jQuery("#work_result").html("");
    jQuery("#add_work").val("");
    jQuery(".artwork-head").removeClass("image-uploaded");
    jQuery(".upload-to-all-text-container").show();
//    jQuery.ajax({
//    url: baseUrl + '/aphro/artwork/account/removeartwork',
//            type: "post",
//            success: function (res1)
//            {
//            }
//    });
    }
    }

</script>
<div class="artwork-head" style="text-align: center;">
    <div class="add-art-label">
        <h1>Add Your Work</h1>
    </div>
    <div class="upload-img-div">
        <img src="<?php
        if ($add_work)
            echo $stat_img;
        else
            echo $stat_img;
        ?>" id="upld_img" alt="" class="arwork-upload-img" style="max-height:150px;max-width:250px;">
        <div id="loading" style="display: none">
            <div id="pre-div" style="">
                <div class="cssload-loader">
                    <div class="cssload-inner cssload-one"></div>
                    <div class="cssload-inner cssload-two"></div>
                    <div class="cssload-inner cssload-three"></div>
                </div>
            </div>
            <!--            <div class="loading">
                            <div class="loading-bar"></div>
                            <div class="loading-bar"></div>
                            <div class="loading-bar"></div>
                            <div class="loading-bar"></div>
                        </div>-->
                        <!--            <img src="<?php echo $loadig_gif; ?>" height="150" width="250">-->
        </div>
        <div class="art-action art-remove-action" style="display: none"><a class="action delete" onclick="remove_art()" href="javascript:;">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-times fa-stack-1x fa-inverse"></i>
                </span></a>
        </div>
    </div>
    <div class="upload-to-all-text-container"><h3>Upload to all products</h3></div>
    <?php //if($av==1) { ?>
    <form class="form form-edit-account" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
        <fieldset class="fieldset info" style="display:none;">
            <?php echo $block->getBlockHtml('formkey') ?>
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Cancel My Account') ?></span></legend><br>
            <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
            <div class="field choice">
                <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" class="checkbox" />
                <label class="label" for="change-email"><span><?php /* @escapeNotVerified */ echo __('Change Email') ?></span></label>
            </div>
            <div class="field choice">
                <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
            </div>
        </fieldset>


        <div class="field add_work required" data-container="change-add_work">
            <label class="label" for="add_work"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
            <div class="control">
                <!--<img src="<?php echo $bu; ?>" alt="" width="150px" height="150px" />-->
                <input type="file" name="add_work" id="add_work" required="true" accept="image/*" onchange="readURL(this);">
                <!--<img src="<?php echo $bu; ?>" alt="" width="150px" height="150px" />-->	 
            </div>
        </div>
        <br />
        <fieldset class="fieldset password" data-container="change-email-password">
            <legend class="legend"><span data-title="change-email-password"><?php /* @escapeNotVerified */ echo __('Change Email and Password') ?></span></legend><br>
            <div class="field email required" data-container="change-email">
                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
                </div>
            </div>
            <div class="field password current required">
                <label class="label" for="current-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
                </div>
            </div>
            <div class="field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
                <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off" />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" >
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirm password required" data-container="confirm-password">
                <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                           data-input="confirm-password"
                           autocomplete="off" />
                </div>
            </div>
            <?php echo $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <!--<button type="submit" class="action save primary" name="upl_art" title="<?php /* @escapeNotVerified */ echo __('Upload new art') ?>"><span><?php /* @escapeNotVerified */ echo __('Upload new art') ?></span></button>-->
                <!--<input type="submit" class="btn btn-warning btn-round" name="upl_art" value="Upload new art">-->
                <!--<input type="text" id="demo_txt" value=""/>-->
                <!--<button type="button" id="upload">Upload new art</button>-->  
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
            </div>
        </div>
    </form>
</div>

<!--<img src="<?php
if ($add_work)
    echo $bu . $add_work;
else
    echo $stat_img;
?>" id="upld_img" alt="" width="150px" height="150px">-->


<!-- Art work result -->
<div id="work_result"></div>
<div class="fullscreen-loader-container" style="display: none">
    <div class="fullscreen-loader">
        <div class="full_table"><div class="full_cell">
        <div id="pre-div" style="">
            <div class="cssload-loader">
                <div class="cssload-inner cssload-one"></div>
                <div class="cssload-inner cssload-two"></div>
                <div class="cssload-inner cssload-three"></div>
            </div>
        </div>
        <div class="fullscreen-text">
            We are creating your customize products. This will take few mins, meanwhile please take a look around our other products by clicking <a href="<?php echo $baseURL; ?>" target="_blank">here</a>.
        </div>
            </div></div>        
    </div>
</div>

<script type="text/javascript">
    require(["jquery"], function ($)
    {
    $('#upload').on('click', function()
    {
    var file = $('#add_work')[0].files[0];
    var reader = new FileReader();
    reader.reload = function (e) {
    //$('#cov_img').attr('src', e.target.result);
    console.log(e.target.result);
    //document.getElementById("work_url").value=e.target.result;
    }
    //console.log(file_r);
//            console.log(reader.result);
//            console.log(reader.readAsDataURL(file));
    //alert(reader.readAsDataURL(file));
//            var formData = new FormData();
//            formData.append('file', $('#add_work')[0].files[0]);
////            console.log($('#add_work')[0].files[0]);
////            alert($('#add_work')[0].files[0]);
//            $.ajax({
//                     url : 'http://35.162.211.144/projects/aphro/artwork/account/upload',
//                     type : 'post',
//                     data : $("#form").serialize(),
//                     dataType : 'json',
//                     processData: false,  // tell jQuery not to process the data
//                     contentType: false,  // tell jQuery not to set contentType
//                     success : function(res) {
//                         console.log(res);
//                         alert(res);
//                     }
//              });
    });
    });</script>
<!--<script type="text/javascript">
    function get_result()
    {
//        require(["jquery"], function ($) {
//            var formData = new FormData();
//            formData.append('file', $('#add_work')[0].files[0]);
////            console.log($('#add_work').files[0]);
////            alert($('#add_work').files[0]);
//
//            $.ajax({
//                    url : 'http://35.162.211.144/projects/aphro/artwork/account/upload',
//                    type : 'POST',
//                    data : formData,
//                    processData: false,  // tell jQuery not to process the data
//                    contentType: false,  // tell jQuery not to set contentType
//                    success : function(res) {
//                        console.log(res);
//                        alert(res);
//                    }
//             });
//        });
    }
</script>-->
<script>
    require([
            "jquery",
            "mage/mage"
    ], function($){
    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
    dataForm.mage('validation', {
<?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
        if (element.prop('id').search('full') !== - 1) {
        var dobElement = $(element).parents('.customer-dob'),
                errorClass = error.prop('class');
        error.insertAfter(element.parent());
        dobElement.find('.validate-custom').addClass(errorClass)
                .after('<div class="' + errorClass + '"></div>');
        }
        else {
        error.insertAfter(element);
        }
        },
                ignore: ':hidden:not(' + ignore + ')'
<?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
<?php endif ?>
    });
    });</script>
<script type="text/x-magento-init">
    {
    "[data-role=change-email], [data-role=change-password]": {
    "changeEmailPassword": {
    "titleChangeEmail": "<?php /* @escapeNotVerified */ echo __('Change Email') ?>",
    "titleChangePassword": "<?php /* @escapeNotVerified */ echo __('Change Password') ?>",
    "titleChangeEmailAndPassword": "<?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>"
    }
    }
    }
</script>
<script type="text/javascript">
    var elems_arr = [];
    function enable_art(a){
    jQuery("#" + a).hide();
    jQuery("#" + a).closest('.action-area').children('.ds-bt').show();
    var elems_val = jQuery("#" + a).val();
    elems_arr.push(elems_val);
    jQuery("#art_enb").val(JSON.stringify(elems_arr));
    }
    function disable_art(b){

    jQuery("#" + b).hide();
    jQuery("#" + b).closest('.action-area').children('.en-bt').show();
    var removeItem = jQuery("#" + b).val();
    var value1 = jQuery('#art_enb').val(); //retrieve array
    value1 = JSON.parse(value1);
    y = jQuery.grep(elems_arr, function(value) {
    return value != removeItem;
    });
    jQuery("#art_enb").val(JSON.stringify(y));
    elems_arr = y;
    }
</script>
<style>
    .loading {
        position: absolute;
        top: 50%;
        left: 50%;
    }
    .loading-bar {
        display: inline-block;
        width: 4px;
        height: 18px;
        border-radius: 4px;
        animation: loading 1s ease-in-out infinite;
    }
    .loading-bar:nth-child(1) {
        background-color: #3498db;
        animation-delay: 0;
    }
    .loading-bar:nth-child(2) {
        background-color: #3498db;
        animation-delay: 0.09s;
    }
    .loading-bar:nth-child(3) {
        background-color: #3498db;
        animation-delay: .18s;
    }
    .loading-bar:nth-child(4) {
        background-color: #3498db;
        animation-delay: .27s;
    }

    @keyframes loading {
        0% {
            transform: scale(1);
        }
        20% {
            transform: scale(1, 2.2);
        }
        40% {
            transform: scale(1);
        }
    }

</style>