<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
//$artist = $_REQUEST['artist'];
//print_r($artist);
//exit();
//$url = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$artist = $this->getRequest()->getParam('id');
//print_r($artist);
//print_r($url);
//exit();
//$artist = 35;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$media_url=$objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
//$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
//$currency = $objectManager->get('\Magento\Directory\Model\Currency');
//$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
try {
    if ($customerSession->isLoggedIn()) {
        $cid = $customerSession->getCustomer()->getId();
        //$name = $customerSession->getCustomer()->getName(); 
        ?>
        <input type="hidden" id="cust_id" name="cust_id" value="<?php echo $cid; ?>">
        <?php
    }

    $connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
//$result1 = $connection->fetchAll("SELECT * FROM art_table");
    $result1 = $connection->fetchAll("SELECT * FROM art_table WHERE art_user =" . $artist);
    ?>

    <div class="container">
   
        <?php
        $media_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $baseURL = $storeManager->getStore()->getBaseUrl();
        $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
        $customer = $customerRepository->getById($artist);
        $customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($artist);
        $pslogin = $storeManager->getStore()->getBaseUrl() . "pub/media/pslogin/photo/";
        $bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
        $base_url = $storeManager->getStore()->getBaseUrl();
        $edit = $storeManager->getStore()->getBaseUrl() . "customer/account/edit";
//    $followers = $storeManager->getStore()->getBaseUrl() . "#";
        $followers = $storeManager->getStore()->getBaseUrl() . "artwork/account/artistfollowers/id/" . $artist;
        $following = $storeManager->getStore()->getBaseUrl() . "#";
        $favorited = $storeManager->getStore()->getBaseUrl() . "#";
//    $followers = $storeManager->getStore()->getBaseUrl() . "artwork/account/followers";
//    $following = $storeManager->getStore()->getBaseUrl() . "artwork/account/following";
//    $favorited = $storeManager->getStore()->getBaseUrl() . "artwork/account/favorited";
        $stat_cov = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/cover.jpg";
        $stat_prof = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
        $result2 = $connection->fetchAll("SELECT * FROM plumrocket_sociallogin_account WHERE customer_id=" . $artist);
        $result3 = $connection->fetchAll("SELECT artist_follower_id FROM artist_follow_followers WHERE artist_following_id=" . $artist);
        $result4 = $connection->fetchAll("SELECT artist_following_id FROM artist_follow_followers WHERE artist_follower_id=" . $artist);
        $stat_cov = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/cover.jpg";
        $stat_prof = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
        $stat_prof_img = $storeManager->getStore()->getBaseUrl();
        $isFollower = false;
        if (isset($cid)) {
            $result5 = $connection->fetchAll("SELECT artist_following_id FROM artist_follow_followers WHERE artist_following_id=" . $artist . " AND artist_follower_id = " . $cid);
            if (count($result5)) {
                $isFollower = true;
            }
        }
        $count = count($result2);
        $follow_count = count($result3);
        $following_count = count($result4);
        $prof_img = "";
        $cover_img = "";
        $username = "";
        $png = '.png';
        $artist_first_name = $customer_obj->getData('firstname');
        $artist_last_name = $customer_obj->getData('lastname');
        if ($customer->getCustomAttribute('description')) {
            $description = $customer->getCustomAttribute('description')->getValue();
        }
        if ($customer->getCustomAttribute('uname')) {
            $username = $customer->getCustomAttribute('uname')->getValue();
        }
        if ($count == 1) {
            if ($customer->getCustomAttribute('prof_image')) {
                $prof_img = $customer->getCustomAttribute('prof_image')->getValue();
                $artist_pic = $bu . $prof_img;
            } else {
                $fb_user = $result2[0]['customer_id'];
                $artist_pic = $pslogin . $fb_user . $png;
            }
        } else {
            if ($customer->getCustomAttribute('prof_image')) {
                $prof_img = $customer->getCustomAttribute('prof_image')->getValue();
                $artist_pic = $bu . $prof_img;
            } else {
                $artist_pic = $base_url . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
            }
        }
        if ($customer->getCustomAttribute('cover_image')) {
            $cover_img = $customer->getCustomAttribute('cover_image')->getValue();
        }
        ?>

        <div class="field cover_image" data-container="change-cover_image">
            <label class="label" for="cover_image"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
            <div class="cover_center">
                <img src="<?php
                if ($cover_img)
                    echo $bu . $cover_img;
                else
                    echo $stat_cov;
                ?>" id="cov_img" alt="" width="100%" height="auto">
            </div>
        </div>
         <div class="follow-section">
        <div class="field prof_image" data-container="change-prof_image">
            <label class="label" for="prof_image"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
            <img src="<?php echo $artist_pic; ?>" id="pro_img" alt="" width="100px" height="100px" />
            <span><?php echo $artist_first_name . ' ' . $artist_last_name; ?></span>
        </div>
        <div class="inner-secton">
        <div class="follow">
            <a class="" href="<?php echo $followers; ?>"><span><?php /* @escapeNotVerified */ echo __('Followers') ?></span></a>
            <a class="" href="<?php echo $following; ?>"><span><?php /* @escapeNotVerified */ echo __('Following') ?></span></a>
    <!--        <a class="" href="<?php echo $favorited; ?>"><span><?php /* @escapeNotVerified */ echo __('Favorited') ?></span></a>-->
            <?php //exit ();   ?>

        </div>

        <div class="count-follow">
            <span><?php echo $follow_count; ?></span>
            <span><?php echo $following_count; ?></span>
            <?php
            $whishlishCollection = $objectManager->create('\Magento\Wishlist\Model\ResourceModel\Item\Collection');
            $whishlishCollection1 = $whishlishCollection->addCustomerIdFilter($artist);
            ?>
            <!--<span><?php echo count($whishlishCollection1); ?></span>-->
        </div>

        <div class="editprof-left-field">
            <?php
            if ($customer->getCustomAttribute('facebook')) {
                ?>
                <a target="_blank" href="https://<?php echo $customer->getCustomAttribute('facebook')->getValue(); ?>"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                <?php
            }
            if ($customer->getCustomAttribute('twitter')) {
                ?>
                <a target="_blank" href="https://<?php echo $customer->getCustomAttribute('twitter')->getValue(); ?>"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <?php
            }
            if ($customer->getCustomAttribute('instagram')) {
                ?>
                <a target="_blank" href="https://<?php echo $customer->getCustomAttribute('instagram')->getValue(); ?>"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <?php
            }
            if ($customer->getCustomAttribute('pinterest')) {
                ?>
                <a target="_blank" href="https://<?php echo $customer->getCustomAttribute('pinterest')->getValue(); ?>"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
                <?php
            }
            ?>
            
    <!--<a class="follow" href="<?php ?>"><span><?php /* @escapeNotVerified */ echo __('Follow') ?></span></a>-->
            <?php
            if (isset($cid) && $cid != $artist) {
                $dataFollow = 0;
                $title = __("Follow");
                if ($isFollower) {
                    $dataFollow = 1;
                    $title = __("Unfollow");
                }
                ?>
                                        <!--            <a class="btn yellow" data-follow='<?php echo $dataFollow; ?>' id="follow" onclick="myFunction()" href="javascript:void(0);"><span id="follow_text"><?php /* @escapeNotVerified */ echo $title; ?></span></a>-->
            <?php } ?>
            <div id="result"></div>
        </div> </div>
        <div class="description"> 
            <span>
                <?php
                if ($customer->getCustomAttribute('description')) {
                    echo $customer->getCustomAttribute('description')->getValue();
                }
                ?>
            </span>
        </div>
        <legend class="legend"></legend>
        <div class="followers"><strong>Followers</strong></div>
        <div class="container">
            <div class="row product-list"><?php
                $followersList = $connection->fetchAll("SELECT * FROM artist_follow_followers WHERE artist_following_id=" . $artist . "");
                foreach ($followersList as $key) {
                    $count = 0;
                    $follow_id = $key['artist_follower_id']; // return all follower ids one by one with loop

                    $customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($follow_id);
                    $follow_cust_details = $customerRepository->getById($follow_id);

                    if (count($follow_cust_details) > 0) {

                        if ($follow_cust_details->getCustomAttribute('prof_image')) {
                            $follow_prof = $follow_cust_details->getCustomAttribute('prof_image')->getValue();
                            $follow_prof_pic = $bu . $follow_prof;
                        } else {
                            $follow_prof_pic = $stat_prof_img . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
                        }
                    } else {

                        $result2 = $connection->fetchAll("SELECT * FROM plumrocket_sociallogin_account WHERE customer_id=" . $follow_id);
                        $count = count($result2);
                        if ($count == 1) {
                            $fb_user = $result2[0]['customer_id'];
                            $follow_prof_pic = $pslogin . $fb_user . $png;
                        }
                    }
                    $follower_first_name = $customer_obj->getData('firstname');
                    $follower_last_name = $customer_obj->getData('lastname');
                    ?>
                    <div class="col-lg-4 product-div" style="float: left;margin: 10px;position: relative;">
                        <div class="slide-overlay" style="border: 2px solid gray;">
                            <div class="table-div">
                                <div class="cell-div">
                                    <a href="<?php echo $baseURL; ?>artwork/account/user/id/<?php echo $follow_id; ?>">
                                        <img src="<?php echo $follow_prof_pic; ?>" class="canvas-export" width="40" height="40" alt="">
                                    </a>
                                    <a href="<?php echo $baseURL; ?>artwork/account/user/id/<?php echo $follow_id; ?>">
                                        <div class="follower-name"><?php echo $follower_first_name . " " . $follower_last_name; ?></div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div><?php }
                ?>
            </div>
        </div>                
    </div>    
    </div>
    <?php
    $count1 = 0;
//if ($cid) {
//    $result5 = $connection->fetchAll("SELECT artist_follower_id FROM artist_follow_followers WHERE artist_following_id=" . $artist . " AND artist_follower_id=" . $cid);
//    $count1 = count($result5);
//}
    ?>
                            <!--<input type="hidden" name="count_id" id="count_id" value="<?php echo $count1; ?>">-->
    <input type="hidden" id="artist" name="artist" value="<?php echo $artist; ?>">

    <?php
} catch (Exception $e) {
    echo $e->getMessage();
}
?>