<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */

?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
    	$id = $customerSession->getCustomer()->getId();
	$name = $customerSession->getCustomer()->getName();
		} 
$media_url=$objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION'); 
$result1 = $connection->fetchAll("SELECT * FROM art_table"); 
?>

<div class="container">
<!--<form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('editprof/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">-->
    <!--<fieldset class="fieldset info">-->
        <?php echo $block->getBlockHtml('formkey')?>
        <!--<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('') ?></span></legend>-->


	<?php 
            	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$customerSession = $objectManager->create('Magento\Customer\Model\Session');
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		if($customerSession->isLoggedIn()) {
    		$id = $customerSession->getCustomer()->getId();	
		}
		$customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
		$customer = $customerRepository->getById($id);
		
		$bu =  $storeManager->getStore()->getBaseUrl()."pub/media/customer";
		$edit = $storeManager->getStore()->getBaseUrl()."customer/account/edit";
		$followers = $storeManager->getStore()->getBaseUrl()."artwork/account/followers";
		$following = $storeManager->getStore()->getBaseUrl()."artwork/account/following";
		$favorited = $storeManager->getStore()->getBaseUrl()."artwork/account/favorited";
		$stat_cov =  $storeManager->getStore()->getBaseUrl()."pub/static/frontend/Custom/theme/en_US/images/cover.jpg";
		$stat_prof =  $storeManager->getStore()->getBaseUrl()."pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
            	$prof_img = "";
            	$cover_img = "";
		$username = "";
				if($customer->getCustomAttribute('uname'))
				{
					$username = $customer->getCustomAttribute('uname')->getValue();
				}
            			if($block->getCustomer()->getCustomAttribute('prof_image'))
				{
					$prof_img = $block->getCustomer()->getCustomAttribute('prof_image')->getValue();
				}

 				if($block->getCustomer()->getCustomAttribute('cover_image')) 
            			{
   							
   					$cover_img = $block->getCustomer()->getCustomAttribute('cover_image')->getValue();
   				}
         ?>

         <div class="field cover_image" data-container="change-cover_image">
          <label class="label" for="cover_image"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
		<div class="cover_center">
                    <img src="<?php if($cover_img) echo $bu.$cover_img; else echo $stat_cov; ?>" id="cov_img" alt="" width="100%" height="auto">
		</div>
        </div>

        <div class="field prof_image" data-container="change-prof_image">
          <label class="label" for="prof_image"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
            	<!--<input type="file" name="prof_image" id="prof_image" onchange="profile(this);">-->
		<?php 
		
		$photoPath = $this->helper('Plumrocket\SocialLoginFree\Helper\Data')->getPhotoPath();
		if (isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img!='')
		{ ?>
			<img src="<?php echo $bu.$prof_img; ?>" id="pro_img" alt="" width="100px" height="100px" />
		<?php }
		elseif(isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img=='')
		{ ?>
			<img src="<?php echo $photoPath; ?>" id="pro_img" alt="" width="100px" height="100px" />
		<?php }
		elseif(!isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img!='')
		{ ?>
			<img src="<?php echo $bu.$prof_img; ?>" id="pro_img" alt="" width="100px" height="100px" />
			
		<?php }
		else
		{ ?>
			<img src="<?php echo $stat_prof; ?>" id="pro_img" alt="" width="100px" height="100px" />
		<?php } ?>

		<!--<img id="new_img" src="http://34.208.118.227/projects/aphro/pub/static/frontend/Custom/theme/en_US/images/upload-profile.png" alt="" width="150px" height="150px" />-->
		<span><?php echo $username; ?></span>
        </div>

	<div class="follow">
	<a class="followers" href="<?php echo $followers; ?>"><span><?php /* @escapeNotVerified */ echo __('followers') ?></span></a>
	<a class="following" href="<?php echo $following; ?>"><span><?php /* @escapeNotVerified */ echo __('following') ?></span></a>
	<a class="favorited" href="<?php echo $favorited; ?>"><span><?php /* @escapeNotVerified */ echo __('favorited') ?></span></a>
	<span>What's up!</span>
	</div>
	<div class="count-follow">
	<span>0</span>
	<span>0</span>
	<span>0</span>
	</div>
        
        
        <!--<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>-->
        <div class="field choice" style="display:none;">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?php /* @escapeNotVerified */ echo __('Change Email') ?></span></label>
        </div>
        <div class="field choice" style="display:none;">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
        </div>
        
        
        
        <div class="editprof-left-field">
        <i class="fa fa-facebook-square" aria-hidden="true"></i>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>
        <i class="fa fa-pinterest-p" aria-hidden="true"></i>
	<a class="edit" href="<?php echo $edit; ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
        </div>
	<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('') ?></span></legend>
    <!--</fieldset>-->

    <!--<fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?php /* @escapeNotVerified */ echo __('Change Email and Password') ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>-->
    <!--<div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>-->
<!--</form>-->
</div>
<div class="container">
  <div class="row product-list">
      <?php foreach ($result1 as $key) {?>
        <div class="col-lg-4 product-div" style="width: 250px;float: left;margin: 10px;position: relative;">
        <div class="slide-overlay" style="border: 2px solid gray;height: 300px;width: 240;">
          
          <img src="<?php echo $media_url."customer".$key['art_image'];?>"  style="height: 40%;width: 40%" alt="<?php echo $key['art_title'];?>">  
        </div>
         <div class="preview-info" style="text-align: center">
          <strong><?php echo $key['art_title'];?></strong>
        </div>
	<span class="cust_name">by <?php echo $name; ?><a class="edit" href="#"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a></span>
      </div>
      <?php } ?>
  </div>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?php /* @escapeNotVerified */ echo __('Change Email') ?>",
                "titleChangePassword": "<?php /* @escapeNotVerified */ echo __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>"
            }
        }
    }
</script>

