<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$media_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseURL = $storeManager->getStore()->getBaseUrl();
$currency = $objectManager->get('\Magento\Directory\Model\Currency');
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {
    $cid = $customerSession->getCustomer()->getId();
    $name = $customerSession->getCustomer()->getName();
}
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
//delete un usual artwork
$sql_del = "DELETE FROM art_table WHERE art_title IS NULL AND art_tag IS NULL AND art_cat IS NULL AND art_user=" . $cid;
$connection->query($sql_del);

$result1 = $connection->fetchAll("SELECT * FROM art_table WHERE art_user =" . $cid);
foreach ($result1 as $key) {
    $art_id = $key['art_id'];
    $art_image = $key['art_image'];
    $cat_id = $key['art_cat'];
    $product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id);
    $cat_img = $product->getData('thumbnail');
}
?>

<div class="container">
    <div class="profile_first_Section">
        <?php echo $block->getBlockHtml('formkey') ?><?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        $categoryCollectionFactory = $objectManager->create("Magento\Catalog\Model\ResourceModel\Category\CollectionFactory");
        $categoryHelper = $objectManager->create("Magento\Catalog\Helper\Category");
        $customerSession = $objectManager->create('Magento\Customer\Model\Session');
        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        if ($customerSession->isLoggedIn()) {
            $id = $customerSession->getCustomer()->getId();
        }
        $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
        $customer = $customerRepository->getById($id);

        $bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
        $edit = $storeManager->getStore()->getBaseUrl() . "customer/account/edit";
        $followers = $storeManager->getStore()->getBaseUrl() . "artwork/account/followers";
        $following = $storeManager->getStore()->getBaseUrl() . "artwork/account/following";
        $favorited = $storeManager->getStore()->getBaseUrl() . "artwork/account/favorited";
        $stat_cov = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/cover.jpg";
        $stat_prof = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
        $prof_img = "";
        $cover_img = "";
        $username = "";
        if ($customer->getCustomAttribute('uname')) {
            $username = $customer->getCustomAttribute('uname')->getValue();
        }
        if ($block->getCustomer()->getCustomAttribute('prof_image')) {
            $prof_img = $block->getCustomer()->getCustomAttribute('prof_image')->getValue();
        }
        if ($block->getCustomer()->getCustomAttribute('cover_image')) {
            $cover_img = $block->getCustomer()->getCustomAttribute('cover_image')->getValue();
        }
        ?>

        <div class="field cover_image" data-container="change-cover_image">
            <label class="label" for="cover_image"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
            <div class="cover_center">
                <img src="<?php
                if ($cover_img)
                    echo $bu . $cover_img;
                else
                    echo $stat_cov;
                ?>" id="cov_img" alt="" width="100%" height="auto">
            </div>
        </div>
        <div class="follow-section">
            <div class="field prof_image" data-container="change-prof_image">
                <label class="label" for="prof_image"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label><?php
                $photoPath = $this->helper('Plumrocket\SocialLoginFree\Helper\Data')->getPhotoPath();
                if (isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img != '') {
                    ?>
                    <img src="<?php echo $bu . $prof_img; ?>" id="pro_img" alt="" width="100px" height="100px" /><?php } elseif (isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img == '') {
                    ?>
                    <img src="<?php echo $photoPath; ?>" id="pro_img" alt="" width="100px" height="100px" /><?php } elseif (!isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img != '') {
                    ?>
                    <img src="<?php echo $bu . $prof_img; ?>" id="pro_img" alt="" width="100px" height="100px" /><?php } else {
                    ?>
                    <img src="<?php echo $stat_prof; ?>" id="pro_img" alt="" width="100px" height="100px" /><?php }
                ?>
                <span><?php echo $username; ?></span>
            </div><?php
            $connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
            $result2 = $connection->fetchAll("SELECT artist_follower_id FROM artist_follow_followers WHERE artist_following_id=" . $id);
            $result3 = $connection->fetchAll("SELECT artist_following_id FROM artist_follow_followers WHERE artist_follower_id=" . $id);
            $follow_count = count($result2);
            $following_count = count($result3);
            ?>
            <div class="inner-secton">
                <div class="follow">
                    <a class="followers" href="<?php echo $followers; ?>"><span><?php /* @escapeNotVerified */ echo __('Followers') ?></span></a>
                    <a class="following" href="<?php echo $following; ?>"><span><?php /* @escapeNotVerified */ echo __('Following') ?></span></a>
                    <a class="favorited" href="<?php echo $favorited; ?>"><span><?php /* @escapeNotVerified */ echo __('Favorited') ?></span></a>
<!--                    <span>What's up!</span>-->
                   
                </div>
                <div class="count-follow">
                    <span><?php echo $follow_count; ?></span>
                    <span><?php echo $following_count; ?></span>
                    <?php
                    $whishlishCollection = $objectManager->create('\Magento\Wishlist\Model\ResourceModel\Item\Collection');
                    $whishlishCollection1 = $whishlishCollection->addCustomerIdFilter($id);
                    ?>
                    <span><?php echo count($whishlishCollection1); ?></span>
                </div>
                <!--<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
    
                <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
                <?php endif ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
                <?php endif ?>
                <?php if ($_gender->isEnabled()): ?>
                    <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
                <?php endif ?>-->
                <div class="field choice" style="display:none;">
                    <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" class="checkbox" />
                    <label class="label" for="change-email"><span><?php /* @escapeNotVerified */ echo __('Change Email') ?></span></label>
                </div>
                <div class="field choice" style="display:none;">
                    <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
                </div>
                <div class="editprof-left-field">
                    <?php
                    if ($block->getCustomer()->getCustomAttribute('facebook')) {
                        ?>
                        <a target="_blank" href="https://<?php echo $block->getCustomer()->getCustomAttribute('facebook')->getValue(); ?>"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                        <?php
                    }
                    if ($block->getCustomer()->getCustomAttribute('twitter')) {
                        ?>
                        <a target="_blank" href="https://<?php echo $block->getCustomer()->getCustomAttribute('twitter')->getValue(); ?>"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <?php
                    }
                    if ($block->getCustomer()->getCustomAttribute('instagram')) {
                        ?>
                        <a target="_blank" href="https://<?php echo $block->getCustomer()->getCustomAttribute('instagram')->getValue(); ?>"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        <?php
                    }
                    if ($block->getCustomer()->getCustomAttribute('pinterest')) {
                        ?>
                        <a target="_blank" href="https://<?php echo $block->getCustomer()->getCustomAttribute('pinterest')->getValue(); ?>"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
                        <?php
                    }
                    ?>  
                    <a class="edit" href="<?php echo $edit; ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
                </div>
            </div>
        </div>
        <div class="description">
            <span>
                <?php
                if ($block->getCustomer()->getCustomAttribute('description')) {
                    echo $block->getCustomer()->getCustomAttribute('description')->getValue();
                }
                ?>
            </span>
        </div>
        <legend class="legend"></legend>
        <div class="dropdown1">
            <a class="dropbtn"> <i class="fa fa-bars" aria-hidden="true"></i> <i class="fa fa-caret-down" aria-hidden="true"></i> Artwork Category<?php
                if (isset($_REQUEST['category'])) {
                    $category = $objectManager->create('Magento\Catalog\Model\Category')->load($_REQUEST['category']);
                    ?> - <strong><?php echo $category->getName(); ?></strong><?php
                }
                ?></a>
            <div id="myDropdown" class="dropdown-content">
                <ul>
                    <li>
                        <a href="<?php echo $storeManager->getStore()->getBaseUrl() . "artwork/account/shop"; ?>" class="art-cat-link <?php
                        if (!isset($_REQUEST['category'])) {
                            echo 'art-active';
                        }
                        ?>"><?php echo "All Category" ?></a>
                    </li>
                    <?php
                    $selectedCategory = (isset($_REQUEST['category']) && $_REQUEST['category']) ? $_REQUEST['category'] : false;
                    $collection = $categoryCollectionFactory->create();
                    $collection->addAttributeToSelect('*');

                    $collection->addIsActiveFilter();

                    $collection->addLevelFilter(2);

                    foreach ($collection as $category) {
                        if (strtolower($category->getName()) == "default category")
                            continue;
                        $category = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
                        $categoryId = $category->getId();
                        $childCategories = explode(",", $category->getChildren());
                        ?>
                        <li>
                            <a href="javascript:void(0)" class="art-cat-link level-1 <?php
                            if ($selectedCategory && ($selectedCategory == $categoryId || in_array($selectedCategory, $childCategories))) {
                                echo 'art-active';
                            }
                            ?>"><?php echo $category->getName(); ?></a>
                               <?php
                               if (count($childCategories)) {
                                   echo "<ul>";
                                   foreach ($childCategories as $child) {
                                       $child = $objectManager->create('Magento\Catalog\Model\Category')->load($child);
                                       $childId = $child->getId();
                                       ?>   
                                    <a href="<?php echo $storeManager->getStore()->getBaseUrl() . "artwork/account/shop?category=" . $childId; ?>" class = "art-cat-link level-2 <?php
                                    if ($selectedCategory && ($selectedCategory == $childId)) {
                                        echo 'art-active';
                                    }
                                    ?>"><?php echo $child->getName();
                                    ?>                                   
                                    </a>
                                    <?php
                                }
                                echo "</ul>";
                            }
                            ?>
                        </li>
                        <?php
                    }
                    ?>                                       
                </ul>
            </div>         
        </div> 
    </div>
</div>
<div class="container">
    <div class="row product-list">
        <div class="all-products"><?php
//            $tempQuery = $connection->fetchAll("SELECT * FROM art_enable_prouct WHERE artist_id = 137");
//            foreach ($tempQuery as $tempRecord) {
//                $product = $objectManager->get('Magento\Catalog\Model\Product')->load(intval($tempRecord['art_product']));
//                $categories = [];
//                $categories = $product->getCategoryIds();
//                $category = $categories[0];                
//                $sql1 = "UPDATE art_enable_prouct SET art_product_category=$category WHERE id=" . $tempRecord['id'];
//                $connection->query($sql1);
//            }

            if (isset($_REQUEST['category'])) {
                foreach ($result1 as $key) {
                    $art_id = $key['art_id'];
                    $artwork_category = $_REQUEST['category'];
                    //echo "SELECT * FROM artwork_category WHERE artwork_id=".$art_id." AND artwork_category_id =". $artwork_category;die;                    
                    $result2 = $connection->fetchAll("SELECT * FROM art_enable_prouct WHERE art_id=" . $art_id . " AND art_product_category =" . $artwork_category . " AND art_status=1");
                    if (count($result2) > 0) {
                        $cat_id2 = $result2[0]['art_product'];
                        $product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id2);
                        $cat_img = $product->getData('thumbnail');
                        if ($product->getTypeId() != "simple") {
                            $price = $product->getSpecialPrice();
                        } else {
                            $price = $product->getPrice();
                        }
                        $formattedPrice = $priceHelper->currency($price, true, false);
                        ?>
                        <div class="col-lg-4 product-div" style="width: 250px;margin: 10px;position: relative;">
                            <div class="slide-overlay" style="border: 2px solid gray;height: 300px;width: 240;">
                                <div class="img-cell">
                                    <a href="<?php echo $baseURL . $product->getData("url_key"); ?>" target="_blank">
                                        <div class="img-middle">
                <!--                                <img src="<?php echo $media_url . "artwork/" . $key['art_image']; ?>" class="canvas-export" alt="<?php echo $key['art_title']; ?>">-->
                                            <img src="<?php echo $media_url . "catalog/product" . $cat_img; ?>"  style="height: 100%;width: 100%" alt="<?php echo $product->getName(); ?>">
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="art-block">
                                <div class="title-tag-price">                                    
                                    <a href="<?php echo $baseURL . $product->getData("url_key"); ?>" target="_blank"><strong><?php echo $key['art_title']; ?> </strong></a>&nbsp;<strong class="price" style="width:70px;"><?php echo $formattedPrice; ?></strong>
                                </div>
                                <div class="name-edit">
                                    <span class="cust_name">by <?php echo $name; ?><a class="edit" href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>artwork/account/edit/id/<?php echo $art_id; ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a></span>
                                </div>
                            </div>
                        </div><?php
                    }
                }
            } else {
                foreach ($result1 as $key) {
                    $cat_id2 = $key['art_cat'];
                    $art_id = $key['art_id'];
                    $product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id2);
                    $cat_img = $product->getData('thumbnail');
                    if ($product->getTypeId() != "simple") {
                        $price = $product->getSpecialPrice();
                    } else {
                        $price = $product->getPrice();
                    }
                    $formattedPrice = $priceHelper->currency($price, true, false);
                    ?>
                    <div class="col-lg-4 product-div" style="width: 250px;margin: 10px;position: relative;">
                        <div class="slide-overlay" style="border: 2px solid gray;height: 300px;width: 240;">
                            <div class="img-cell">
                                <a href="<?php echo $baseURL . $product->getData("url_key"); ?>" target="_blank">
                                    <div class="img-middle">                                    
            <!--                                <img src="<?php echo $media_url . "artwork/" . $key['art_image']; ?>" class="canvas-export" alt="<?php echo $key['art_title']; ?>">-->
                                        <img src="<?php echo $media_url . "catalog/product" . $cat_img; ?>"  style="height: 100%;width: 100%" alt="<?php echo $product->getName(); ?>">                                    
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="art-block">
                            <div class="title-tag-price">
                                <a href="<?php echo $baseURL . $product->getData("url_key"); ?>" target="_blank"><strong><?php echo $key['art_title']; ?> </strong></a>&nbsp;<strong class="price" style="width:70px;"><?php echo $formattedPrice; ?></strong>
                            </div>
                            <div class="name-edit">
                                <span class="cust_name">by <?php echo $name; ?><a class="edit" href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>artwork/account/edit/id/<?php echo $art_id; ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a></span>
                            </div>
                        </div>
                    </div><?php
                }
            }
            ?>

        </div>
    </div>
</div>
<script>
    require([
            "jquery",
            "mage/mage"
    ], function($){
    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
    dataForm.mage('validation', {
<?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
        if (element.prop('id').search('full') !== - 1) {
        var dobElement = $(element).parents('.customer-dob'),
                errorClass = error.prop('class');
        error.insertAfter(element.parent());
        dobElement.find('.validate-custom').addClass(errorClass)
                .after('<div class="' + errorClass + '"></div>');
        }
        else {
        error.insertAfter(element);
        }
        },
                ignore: ':hidden:not(' + ignore + ')'
<?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
<?php endif ?>
    });
    $('.dropbtn').click(function(){
    $('#myDropdown').slideToggle();
    });
    });
</script>
<script type="text/x-magento-init">
    {
    "[data-role=change-email], [data-role=change-password]": {
    "changeEmailPassword": {
    "titleChangeEmail": "<?php /* @escapeNotVerified */ echo __('Change Email') ?>",
    "titleChangePassword": "<?php /* @escapeNotVerified */ echo __('Change Password') ?>",
    "titleChangeEmailAndPassword": "<?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>"
    }
    }
    }

</script>

