<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$media_url=$objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
    $cid = $customerSession->getCustomer()->getId();	
}

$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION'); 

//delete un usual artwork
$sql_del = "DELETE FROM art_table WHERE art_title IS NULL AND art_tag IS NULL AND art_cat IS NULL AND art_user=".$cid;
$connection->query($sql_del);	

//$result1 = $connection->fetchAll("SELECT * FROM art_table"); 
$result1 = $connection->fetchAll("SELECT * FROM art_table WHERE art_user =".$cid." ORDER BY art_id DESC");
foreach ($result1 as $key)
	{	$art_id = $key['art_id'];
		$art_image = $key['art_image'];
		$cat_id = $key['art_cat'];
		$product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id);
		$cat_img =  $product->getData('thumbnail');
		$price = $product->getPrice();
			
	}

	 //exit();

//print_r($product); die;
/*foreach ($collection as $product)
{
	$abc = $product->getData();
	$pro_img = $product->getData('thumbnail');
	print_r($pro_img);
}
	$xyz = $pro_img->getData($cat_id);
	 die;*/
?>
<input type="hidden" value="<?php echo $media_url."artwork"; ?>">
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h4>ArtWork Portfolio</h4>
    </div>
  </div>
  <hr>
  <div class="row product-list">
      <?php foreach ($result1 as $key) {
	$cat_id = $key['art_cat'];
	$product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id);
	$cat_img =  $product->getData('thumbnail');
	$price = $product->getPrice();
	//echo $cat_img; 
?>

	
        <div class="col-lg-4 product-div" style="width: 250px;float: left;margin: 10px;position: relative;">
        <div class="slide-overlay" style="border: 2px solid gray;height: 300px;width: 240;">
            <div class="img-cell">
        <div class="img-middle">
          <img src="<?php echo $media_url."artwork/".$key['art_image'];?>" class="canvas-export" alt="<?php echo $key['art_title'];?>">
	<img src="<?php echo $media_url."catalog/product".$cat_img;?>"  style="height: 100%;width: 100%" alt="<?php echo $product->getName();?>">  
	</div>
	</div>
        </div>
         <div class="preview-info" style="text-align: center">
          <strong><?php echo $key['art_title'];?></strong>
        </div>
      </div>
      <?php } ?>
  </div>
  
