<?php //if ($block->canShowBlock()): ?>
<?php //echo "work";die;?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
              <?php if (!$wrapOptions): ?>
                <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options2') ?></strong>
                <dl class="filter-options" id="narrow-by-list">
                  <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                      <dt role="heading" aria-level="3" class="filter-options-title"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                      <dd class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></dd>
                    <?php endif; ?>
                  <?php endforeach; ?>
                  <?php if ($wrapOptions): ?>
                  <?php
                  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                  $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                  $base_url = $storeManager->getStore()->getBaseUrl();
                  $connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
                  ?>
                  <dt role="heading" aria-level="3" class="filter-options-title"><?php echo "Artist" ?></dt>
                  <?php
                      //Get artist list
                      $artist_list = $connection->fetchAll("SELECT art_user FROM art_table GROUP BY art_user");
                      $artist_count = count($artist_list);//Total Artist
                  ?>
                  <dd class="filter-options-content">
                    <ol class="items">
                      <?php 
                      foreach ($artist_list as $al){
                        $artist_id = $al['art_user'];
                        $artist_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($artist_id);
                        $artist_fname =  $artist_obj->getData('firstname');
                        $artist_lname =  $artist_obj->getData('lastname');  
                        
                        ?>
                        <li class="item"><input type="checkbox" name="artist_name[]" value="<?php echo $artist_id;?>"/><?php echo $artist_fname." ".$artist_lname?></li>
                        <!--<li class="item"><a href="<?php echo $base_url."catalog/account/catalog/id/".$artist_id;?>"><?php echo $artist_fname." ".$artist_lname?></a></li>-->
                        <?php
                      }
                      ?>
                    </ol>
                  </dd>
                  <?php
                    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                    if($customerSession->isLoggedIn()) {
                      $id = $customerSession->getCustomer()->getId();
                      //Get following id list
                      
                      $following_list = $connection->fetchAll("SELECT artist_following_id FROM artist_follow_followers WHERE artist_follower_id=". $id);
                      $following_count = count($following_list);//Total following
                      if($following_count>0){
                      ?>
                      <dt role="heading" aria-level="3" class="filter-options-title"><?php echo "Following" ?></dt>
                        <dd class="filter-options-content">
                          <ol class="items">
                                <?php 
                                foreach ($following_list as $fl){
                                    $following_id=  $fl['artist_following_id'];
                                    //echo $following_id;
                                    $customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($following_id);
                                    $following_first_name =  $customer_obj->getData('firstname');
                                    $following_last_name =  $customer_obj->getData('lastname'); ?>
                                    <li class="item"><input type="checkbox" name="follower_name[]" value="<?php echo $following_id;?>"/><?php echo $following_first_name." ".$following_last_name?></li>
                                    <!--<li class="item"><a href="<?php echo $base_url."catalog/account/following/id/".$following_id;?>"><?php echo $following_first_name." ".$following_last_name?></a></li>-->
                                    <?php
                                }
                                ?>
                          </ol>
                        </dd>
                      <?php 
                      }
                    }?>
                </dl>
              <?php endif; ?>
        </div>
    </div>
<?php //endif; ?>
