<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$pslogin = $storeManager->getStore()->getBaseUrl() . "pub/media/pslogin/photo/";
$bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
$base_url = $storeManager->getStore()->getBaseUrl();
$stat_prof = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
?>
<?php
    $_items = $block->getReviewsCollection()->getItems();
    $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)):?>
<div class="block review-list" id="customer-reviews">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('') ?></strong>
    </div>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
        <?php foreach ($_items as $_review):?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                <div class="review-title" itemprop="name" style="display:none;"><?php echo $block->escapeHtml($_review->getTitle()) ?></div>
                <?php if (count($_review->getRatingVotes())): ?>
                    <div class="review-ratings">
                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <span class="label rating-label"><span>
                          <?php $artist=$_review->getData('customer_id');
                          $customer = $customerRepository->getById($artist);
                           $customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($artist);
                           if ($customer->getCustomAttribute('prof_image')) {
                           $prof_img = $customer->getCustomAttribute('prof_image')->getValue();
                           $artist_pic = $bu . $prof_img;
                            } else {
                            $artist_pic = $base_url . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png"; }


                            ?>
                          <img src="<?php echo $artist_pic; ?>"></span></span>
                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
	                        <meta itemprop="worstRating" content = "1"/>
	                        <meta itemprop="bestRating" content = "100"/>
                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                            </span>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    </div>
               <?php else: ?>
                  <p class="not-rew"> Be the first to review this product</p>
                <?php endif; ?>

                <div class="review-details">
                    <p class="review-author">
                        <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('')?></span>
                        <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                    </p>
                    <p class="review-date">
                        <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                        <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>">

                          <?php $now = date("Y-m-d h:i:s"); // or your date as well

                          $now = strtotime($now);

                          $your_date = strtotime($_review->getCreatedAt());
                          $datediff = $now - $your_date;
                          echo floor($datediff / (60 * 60 * 24))." Days Ago";
                          ?></time>
                    </p>
                </div>
		<div class="review-content" itemprop="description">

                          <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php else: ?>
                  <p class="not-rew"> Be the first to review this product</p>
                <?php endif; ?>
