<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if ($_key != 'position' && $_key !='default_view' && $_key !='relevance') : // Remove "Position" from the sort option list ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endif; ?>
        <?php endforeach; ?>
            <option class="popularity" <?php if(isset($_REQUEST['product_list_order'])){ if($_REQUEST['product_list_order']=="Popularity"){ echo 'selected';}}?>> Popularity</option>
            <option class="new-arrival" <?php if(isset($_REQUEST['product_list_order'])){ if($_REQUEST['product_list_order']=="New Arrival"){ echo 'selected';}}?>> New Arrival </option>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
