<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */

?>
<div class="container">
<form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('editprof/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('') ?></span></legend>


	<?php 
            	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
					$bu =  $storeManager->getStore()->getBaseUrl()."pub/media/customer";
		$stat_cov =  $storeManager->getStore()->getBaseUrl()."pub/static/frontend/Custom/theme/en_US/images/cover.jpg";
		$stat_prof =  $storeManager->getStore()->getBaseUrl()."pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
            	$prof_img = "";
            	$cover_img = "";
            			if($block->getCustomer()->getCustomAttribute('prof_image') && $block->getCustomer()->getCustomAttribute('cover_image')) 
            			{
   							$prof_img = $block->getCustomer()->getCustomAttribute('prof_image')->getValue();
   							$cover_img = $block->getCustomer()->getCustomAttribute('cover_image')->getValue();
   						}
         ?>

         <div class="field cover_image required" data-container="change-cover_image">
          <label class="label" for="cover_image"><span><?php /* @escapeNotVerified */ echo __('Cover Image') ?></span></label>
            <div class="control">
		<div class="cover_center">
                    <input type="file" name="cover_image" id="cover_image" onchange="readURL(this);">
                    <div class="img-center">
                        <img class="cover_img_icon" src="http://34.208.118.227/projects/aphro/pub/static/frontend/Custom/theme/en_US/images/upload.png">
                    </div>
                    <img src="<?php if($cover_img) echo $bu.$cover_img; else echo $stat_cov; ?>" id="cov_img" alt="" width="100%" height="auto">
		</div>
                </div>
        </div>

        <div class="field prof_image required" data-container="change-prof_image">
          <label class="label" for="prof_image"><span><?php /* @escapeNotVerified */ echo __('Profile Image') ?></span></label>
            <div class="control">
		<div class="profile_center">
            	<input type="file" name="prof_image" id="prof_image" onchange="profile(this);">
		<?php 
		
		$photoPath = $this->helper('Plumrocket\SocialLoginFree\Helper\Data')->getPhotoPath();
		if (isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img!='')
		{ ?>
			<img src="<?php echo $bu.$prof_img; ?>" id="pro_img" alt="" width="150px" height="150px" />
		<?php }
		elseif(isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img=='')
		{ ?>
			<img src="<?php echo $photoPath; ?>" id="pro_img" alt="" width="150px" height="150px" />
		<?php }
		elseif(!isset($_SESSION['customer_base']['pslogin_referer_store']) && $prof_img!='')
		{ ?>
			<img src="<?php echo $bu.$prof_img; ?>" id="pro_img" alt="" width="150px" height="150px" />
			
		<?php }
		else
		{ ?>
			<img src="<?php echo $stat_prof; ?>" id="pro_img" alt="" width="150px" height="150px" />
		<?php } ?>



		</div>
            </div>
        </div>
        
        
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field choice" style="display:none;">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?php /* @escapeNotVerified */ echo __('Change Email') ?></span></label>
        </div>
        <div class="field choice" style="display:none;">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
        </div>
        
        
        
        <div class="field description required" data-container="change-description">
            <label class="label" for="description" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Description') ?></span></label>
            <div class="control">
                <!--<input type="text" name="description" id="description" autocomplete="description" data-input="change-description" value="<?php if($block->getCustomer()->getCustomAttribute('description')) {
   echo $block->getCustomer()->getCustomAttribute('description')->getValue();
}?>" title="<?php /* @escapeNotVerified */ echo __('Description') ?>" class="input-text" data-validate="{}" />-->
						<textarea name="description" id="description" placeholder="Description" title="<?php /* @escapeNotVerified */ echo __('Description') ?>" class="input-text" >
						<?php if($block->getCustomer()->getCustomAttribute('description')) {
   echo $block->getCustomer()->getCustomAttribute('description')->getValue(); }?>
						</textarea>
            </div>
        </div>
        <div class="editprof-left-field">
        <i class="fa fa-facebook-square" aria-hidden="true"></i>
        <div class="field facebook required" data-container="change-facebook">
            <label class="label" for="facebook" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Facebook') ?></span></label>
            <div class="control">
                <input type="text" name="facebook" id="facebook" placeholder="Facebook" autocomplete="facebook" data-input="change-facebook" value="<?php if($block->getCustomer()->getCustomAttribute('facebook')) {
   echo $block->getCustomer()->getCustomAttribute('facebook')->getValue();
}?>" title="<?php /* @escapeNotVerified */ echo __('Facebook') ?>" class="input-text" data-validate="{}" />
            </div>
        </div>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <div class="field twitter required" data-container="change-twitter">
            <label class="label" for="twitter" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Twitter') ?></span></label>
            <div class="control">
                <input type="text" name="twitter" id="twitter" placeholder="Twitter" autocomplete="twitter" data-input="change-twitter" value="<?php if($block->getCustomer()->getCustomAttribute('twitter')) {
   echo $block->getCustomer()->getCustomAttribute('twitter')->getValue();
}?>" title="<?php /* @escapeNotVerified */ echo __('Twitter') ?>" class="input-text" data-validate="{}" />
            </div>
        </div>
        <i class="fa fa-instagram" aria-hidden="true"></i>
        <div class="field instagram required" data-container="change-instagram">
            <label class="label" for="instagram" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Instagram') ?></span></label>
            <div class="control">
                <input type="text" name="instagram" id="instagram" placeholder="Instagram" autocomplete="instagram" data-input="change-instagram" value="<?php if($block->getCustomer()->getCustomAttribute('instagram')) {
   echo $block->getCustomer()->getCustomAttribute('instagram')->getValue();
}?>" title="<?php /* @escapeNotVerified */ echo __('Instagram') ?>" class="input-text" data-validate="{}" />
            </div>
        </div>
        <i class="fa fa-pinterest-p" aria-hidden="true"></i>
        <div class="field pinterest required" data-container="change-pinterest">
            <label class="label" for="pinterest" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Pinterest') ?></span></label>
            <div class="control">
                <input type="text" name="pinterest" id="pinterest" placeholder="Pinterest" autocomplete="pinterest" data-input="change-pinterest" value="<?php if($block->getCustomer()->getCustomAttribute('pinterest')) {
   echo $block->getCustomer()->getCustomAttribute('pinterest')->getValue();
}?>" title="<?php /* @escapeNotVerified */ echo __('Pinterest') ?>" class="input-text" data-validate="{}" />
            </div>
        </div>
        </div>
    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?php /* @escapeNotVerified */ echo __('Change Email and Password') ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
</div>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?php /* @escapeNotVerified */ echo __('Change Email') ?>",
                "titleChangePassword": "<?php /* @escapeNotVerified */ echo __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>"
            }
        }
    }
</script>
