<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$bu =  $storeManager->getStore()->getBaseUrl()."customer/account/login";
	$register =  $storeManager->getStore()->getBaseUrl()."customer/account/create";

	$logo =  $storeManager->getStore()->getBaseUrl()."pub/media/logo/stores/1/logo.png";
	$home =  $storeManager->getStore()->getBaseUrl();
?>
<center>
<a href="<?php echo $home; ?>" title="Aphro">
        <img src="<?php echo $logo; ?>" alt="Aphro" width="148" height="43">
</a>
</center>
<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Enter your email address to help us identify you.'); ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" placeholder="Email address" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Next') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
	<center>
	<div class="return"><a href="<?php echo $bu; ?>">RETURN TO SIGN IN</a></div>
	<div class="return"><a href="<?php echo $home; ?>">GO TO EC TOP</a></div>
	</center>
</form>
