<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
   $cid = $customerSession->getCustomer()->getId(); }
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base = $storeManager->getStore()->getBaseUrl();
//$customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($cid);
//$customer = $customerRepository->getById($cid);
//$addresses = $customer->getAddresses();
//$billingAddress = $customer->getDefaultBilling();
//print_r($billingAddress); 
//$number =  $customer_obj->getData('firstname');
//exit();
$billingID =  $customerSession->getCustomer()->getDefaultBilling();
$address = $objectManager->create('Magento\Customer\Model\Address')->load($billingID);
$city = $address->getData('city');
$country = $address->getData('country_id');
$postcode = $address->getData('postcode');
$region = $address->getData('region');
$region_id = $address->getData('region_id');
$street = $address->getData('street');
$telephone = $address->getData('telephone');
//exit;
?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<div class="container">
<form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
  <fieldset class="fieldset">
    <legend class="legend"><span style="font-weight:bold;"><?php /* @escapeNotVerified */ echo __('My Shipping Details') ?></span></legend><br>
    <?php echo $block->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
    <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
    <?php echo $block->getNameBlockHtml() ?>
    <div class="field company" style="display:none;">
        <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
        <div class="control">
            <input type="text" name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
        </div>
    </div>
    <div class="field telephone required">
        <label class="label" for="telephone" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
        <div class="control">
            <input type="text" name="telephone" placeholder="Phone Number" value="<?php echo $telephone;//$block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone">
        </div>
    </div>
    <div class="field fax" style="display:none;">
        <label class="label" for="fax"><span><?php /* @escapeNotVerified */ echo __('Fax') ?></span></label>
        <div class="control">
            <input type="text" name="fax" id="fax" title="<?php /* @escapeNotVerified */ echo __('Fax') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
        </div>
    </div>
  </fieldset>
  <fieldset class="fieldset">
    <!--   <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('') ?></span></legend><br> -->
    <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
    <div class="field street required">
        <label for="street_1" class="label" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
        <div class="control">
          <input type="text" name="street[]" placeholder="Street Address" value="<?php echo $street;//$block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"  />
          <div class="nested">
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
              <div class="field additional">
                <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>">
                  <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>">
              </div>
            </div>
          <?php endfor; ?>
        </div>
      </div>
    </div>

    <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
      <div class="field taxvat">
        <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
        <div class="control">
          <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
        </div>
      </div>
    <?php endif; ?>
    <div class="field country required">
      <label class="label" for="country" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
      <div class="control">
        <?php echo $block->getCountryHtmlSelect() ?>
      </div>
    </div>
    <div class="field region required">
      <label class="label" for="region_id" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
      <div class="control">
          <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
            <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
          </select>
          <input type="text" id="region" name="region" value="<?php echo $region;//$block->escapeHtml($block->getRegion()) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
      </div>
    </div>
    <div class="field city required">
      <label class="label" for="city" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
      <div class="control">
        <input type="text" name="city" placeholder="City or Town" value="<?php echo $city;//$block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
      </div>
    </div>
    <div class="field zip required">
      <label class="label" for="zip" style="display:none;"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
      <div class="control">
        <input type="text" name="postcode" placeholder="Postal Code" value="<?php echo $postcode;//$block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
      </div>
    </div>
    <?php if ($block->isDefaultBilling()): ?>
      <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
    <?php elseif ($block->canSetAsDefaultBilling()): ?>
      <div class="field choice set billing" style="display:none;">
        <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
        <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
      </div>
    <?php else: ?>
      <input type="hidden" name="default_billing" value="1" />
    <?php endif; ?>

    <?php if ($block->isDefaultShipping()): ?>
      <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?></div>
    <?php elseif ($block->canSetAsDefaultShipping()): ?>
      <div class="field choice set shipping" style="display:none;">
        <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
        <label class="label" for="primary_shipping"><span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span></label>
      </div>
    <?php else: ?>
      <input type="hidden" name="default_shipping" value="1">
    <?php endif; ?>
    <div class="field user_agree required">
      <label class="label" for="user_agree"><span><?php /* @escapeNotVerified */ echo __('User Agreement') ?></span></label>              
      <div>
        <span>When a product is sold through the website the sale is between you and the customer - Aphro acts as your agent in this process. In order to act as your agent, we need your explicit permission.</span> 
      </div>        
      &nbsp; 
<!--      <div class="control">
        <input type="checkbox" name="user_agree" id="agree" data-validate="{required:true}" class="checkbox" value="1">
        <span>Yes I agree to the Aphro <a href="<?php echo $base.'terms-of-use'?>" target="_blank">User Agreement</a></span>	
      </div>  -->
      <span class="agree" style="display:none;"><?php /* @escapeNotVerified */ echo __('This is a required field.') ?></span>     
    </div>
  </fieldset>
  <div class="actions-toolbar">
    <div class="primary">
      <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
    </div>
    <div class="secondary">
      <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
    </div>
  </div>
</form>
</div>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>

<script>


require([ 'jquery', 'jquery/ui'], function($){ $(document).ready(function($) {

//var confirm=document.getElementById("agree").value;


$('.primary').click(function() {
if(!$('#agree').hasClass("mage-error")) {
$( ".agree" ).show(); }
if($('#agree').hasClass("mage-error")) {
$( ".agree" ).show(); }
//var confirm=document.getElementById("agree").value;

         /*if((confirm.checked==false))
         {
         alert("plz check the checkbox field");
         document.getElementbyId("agree").focus();
         return false;
         }*/
});

$("#agree").click(function(){
if ($("#agree").is(":checked")) {
	$( ".agree" ).hide();
}

});

});
});
</script>
