<!--<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magento_Catalog::css/owl.carousel.min.css') ?>">-->
<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
$blockObj = $block->getLayout()->createBlock('Artist\Artwork\Block\User');
$url = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$pid = $block->getProduct()->getId();
$om = \Magento\Framework\App\ObjectManager::getInstance();
$rf = $om->create('Magento\Review\Model\Review');
$sm = $om->get('\Magento\Store\Model\StoreManagerInterface');
$sid = $sm->getStore()->getId();
$ttype = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
//$con = $om->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
//$rs = $con->fetchAll("SELECT * FROM art_table");
/* foreach ($rs as $key1)
  {
  $pid = $key1['art_cat'];
  $pro = $om->get('Magento\Catalog\Model\Product')->load($pid);
  $rf = $om->get('Magento\Catalog\Block\Product\ReviewRendererInterface')->getReviewsSummaryHtml($pro, $ttype,true);
  //echo $pro;//echo $rf;
  } */ //exit();
$pro = $om->get('Magento\Catalog\Model\Product')->load($pid);
$rf = $om->get('Magento\Catalog\Block\Product\ReviewRendererInterface')->getReviewsSummaryHtml($pro, $ttype, true);
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <?php $newOrderTabbing = array('product.info.description', 'commodity.tab', 'reviews.tab', 'tags.tab'); //custom add ?>

    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($newOrderTabbing as $name):
               ?>
                <?php
                $html = $layout->renderElement($name);


                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title'); ?>
                <div class="data item title" aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>-title" data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>">
                    <a class="data switch" tabindex="-1" data-toggle="switch" href="#<?php /* @escapeNotVerified */ echo $alias; ?>" id="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                        <?php if ($label == "Features") { ?>
                            <i class="fa fa-info-circle" aria-hidden="true"></i>
                        <?php } elseif ($label == "Commodity") { ?>
                            <i class="fa fa-commodity" aria-hidden="true" id="commodity_no">

                              </i><?php
                        } elseif ($label == "Reviews") {
                            echo '';
                        } elseif ($label == "Tags") { ?>
                            <i class="fa fa-tags" aria-hidden="true"></i><?php
                        } else {
                            echo $rf;
                        } ?>
                    </a>
                    <?php if ($label == "Reviews") { ?> <i class="fa fa-review" aria-hidden="true"></i><?php } ?>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <span class="product-title"><?php /* @escapeNotVerified */ echo $label; ?></span>
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()) {
    $cid = $customerSession->getCustomer()->getId();
    ?>
    <input type="hidden" id="cust_id" name="cust_id" value="<?php echo $cid; ?>">
    <?php
}
$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
//$follow = $storeManager->getStore()->getBaseUrl()."#";
$storeId = $storeManager->getStore()->getId();
$media_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$username = "";
$art_prof_pic = "";
$pslogin = $storeManager->getStore()->getBaseUrl() . "pub/media/pslogin/photo/";
$bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
$png = '.png';
$stat_prof_img = $storeManager->getStore()->getBaseUrl();
$userid = $pro->getData("yourcustomattribute_id");
$_productId = $block->getProduct()->getId();
$currentProduct = $objectManager->get('Magento\Catalog\Model\Product')->load($_productId);
$artworkId = $currentProduct->getData("product_artwork_id");
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
$result = $connection->fetchAll("SELECT * FROM art_table WHERE art_user=" . $userid);
//if (isset($cid)) {
//    $result = $connection->fetchAll("SELECT * FROM art_table WHERE NOT art_user=" . $cid);
//} else {
//    $result = $connection->fetchAll("SELECT * FROM art_table");
//}
$ct = 0;
$arr = array();
?>

<?php
foreach ($result as $key) {
    $count = 0;
    $art_user = $key['art_user'];
    $cat_id = $key['art_cat'];
    $product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id);
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    //$reviewFactory->getEntitySummary($product, $storeId);
    $reviewFactory = $objectManager->get('Magento\Catalog\Block\Product\ReviewRendererInterface')->getReviewsSummaryHtml($product, $templateType, true);
    $ratingSummary = $product->getRatingSummary()->getRatingSummary();
    $ratingsCount = $product->getRatingSummary()->getReviewsCount();
    $price = $product->getPrice();
    $cat_img = $product->getData('thumbnail');
    $formattedPrice = $priceHelper->currency($price, true, false);
    $result1 = $connection->fetchAll("SELECT * FROM plumrocket_sociallogin_account WHERE customer_id=" . $art_user);
    $count = count($result1);
    //print_r($art_user);
    $customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($art_user);
    $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
    $cust_details = $customerRepository->getById($art_user);
    if ($cust_details->getCustomAttribute('uname')) {
        $username = $cust_details->getCustomAttribute('uname')->getValue();
    }
    if ($count == 1) {
        if ($cust_details->getCustomAttribute('prof_image')) {
            $art_prof_pic = $cust_details->getCustomAttribute('prof_image')->getValue();
            $artist_pic = $bu . $art_prof_pic;
        } else {
            $fb_user = $result1[0]['customer_id'];
            $artist_pic = $pslogin . $fb_user . $png;
        }
    } else {
        if ($cust_details->getCustomAttribute('prof_image')) {
            $art_prof_pic = $cust_details->getCustomAttribute('prof_image')->getValue();
            $artist_pic = $bu . $art_prof_pic;
        } else {
            $artist_pic = $stat_prof_img . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
        }
    }

    $follower_first_name = $customer_obj->getData('firstname');
    $follower_last_name = $customer_obj->getData('lastname');
    $follower_name = $follower_first_name . " " . $follower_last_name;
    ?>
<?php } ?>
<div class="product-section-slide">
    <div class="product-section">
        <?php
        if (!in_array($follower_name, $arr)) {
            array_push($arr, $follower_name);
            ?>
            <img src="<?php echo $artist_pic; ?>" width="40" height="40" alt="">
            <span id="follower_name"><a href="<?php echo $blockObj->getUserUrl($art_user) //echo $stat_prof_img.'artwork/account/user/'.'?='.$art_user;             ?>"><?php echo $follower_name . "'s Shop"; ?></a></span>
            <input type="hidden" id="artist" name="artist" value="<?php echo $art_user; ?>">
            <?php if (isset($cid)) { ?>
                                                      <!--        <button class="btn btn-warning btn-round follow" name="follow" id="follow" data-follow = '0' onclick="myFunction(this)" title="<?php /* @escapeNotVerified */ echo __('Follow') ?>"><span id="follow_text"><?php /* @escapeNotVerified */ echo __('Follow') ?></span></button>		-->
            <?php } ?>
            <div id="result"></div>
            <?php
$result4 = $connection->fetchAll("SELECT artist_following_id FROM artist_follow_followers WHERE artist_follower_id=" . $art_user);
 $isFollower = false;
 if (isset($cid)) {
   $result5 = $connection->fetchAll("SELECT artist_following_id FROM artist_follow_followers WHERE artist_following_id=" . $art_user . " AND artist_follower_id = " . $cid);
   if (count($result5)) {
     $isFollower = true;
    }
 }
if (isset($cid) ) {
  $dataFollow = 0;
  $title = __("Follow");
  if ($isFollower) {
    $dataFollow = 1;
    $title = __("Unfollow");
  }

if($cid!=$art_user){

  ?>
  <a class="btn yellow" id="follow" data-follow ='<?php echo $dataFollow; ?>' onclick="<?php if(isset($cid)){ echo "myFunction(this)";} else { echo " alert('okk');";}?>" href="javascript:void(0);"><span><?php /* @escapeNotVerified */ echo $title; ?></span></a>
  <?php
}
}
 ?>

        <?php } ?>
    </div>
    <?php echo $block->getLayout()->createBlock('Mageplaza\Productslider\Block\NewProducts')->setTemplate('productslider.phtml')->toHtml(); ?>
</div>
<div class="row product-list">
    <div class="item">
        <!--<div class="col-lg-4 product-div" style="width: 250px;float: left;margin: 10px;position: relative;">
                <div class="slide-overlay" style="border: 2px solid gray;height: 300px;width: 240;">-->

<!--<img src="<?php echo $media_url . "artwork/" . $key['art_image']; ?>" class="canvas-export" width="40" height="40" alt="<?php echo $key['art_title']; ?>">-->
<!--<img src="<?php echo $media_url . "catalog/product" . $cat_img; ?>"  style="height: 100%;width: 100%" alt="<?php echo $product->getName(); ?>">
</div>-->
        <!--<div class="art-block">
               <div class="title-tag-price">
                       <strong><?php echo $key['art_title']; ?></strong>-<strong><?php echo $key['art_tag']; ?></strong>...&nbsp;&nbsp;<strong><?php echo $formattedPrice; ?></strong>
               </div>
               <div class="name-edit">
                       <span class="cust_name">by <?php echo $username; ?></span>
               </div>
       </div>
       </div>-->

    </div>
</div>

<?php
$result2 = $connection->fetchAll("SELECT artist_follower_id FROM artist_follow_followers WHERE artist_following_id=" . $art_user);
$count1 = count($result2);
foreach ($result2 as $key1) {
    $artist_follower_id = $key1['artist_follower_id'];
}
?>


<input type="hidden" name="count_id" id="count_id" value="<?php echo $count1; ?>">
<input type="hidden" name="current_url" id="current_url" value="<?php echo $url; ?>">

<script>
    var count_id = document.getElementById('count_id').value;

    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            // if (count_id == 1) {
            //     jQuery('#follow').attr('data-follow', 1);
            //     jQuery('#follow_text').text('Unfollow');
            // } else {
            //     jQuery('#follow').attr('data-follow', 0);
            //     jQuery('#follow_text').text('Follow');
            // }
        });
    });
</script>
<script>
    function myFunction()
    {
        var button = document.getElementById('follow');
        var artist = document.getElementById('artist').value;
        var follow = button.getAttribute('data-follow');
//var cust_id = "";
//if(cust_id != null)
//{
        var cust_id = document.getElementById('cust_id').value;
//}
//var current_url = document.getElementById('current_url').value;
        //alert(cust_id);


        jQuery.ajax({
            type: 'POST',
            url: "artwork/index/view",
            data: {"label": artist, "var1": cust_id, "var2": follow},
            //data: data,

            success: function (response) {
                //jQuery('#result').html(response);
                if (follow == 0) {
                    jQuery('#follow').attr('data-follow', 1);
                    jQuery('#follow_text').text('Unfollow');
                } else {
                    jQuery('#follow').attr('data-follow', 0);
                    jQuery('#follow_text').text('Follow');
                }

                //$(".user").html(response);
            },
            error: function (error) {
                jQuery('#result').html(error);
            }
        });
    }
</script>
