<?php
$artist = $this->getRequest()->getParam('id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$media_url=$objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$base_url = $storeManager->getStore()->getBaseUrl();
$currency = $objectManager->get('\Magento\Directory\Model\Currency');
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');

?>
<div class="products wrapper grid products-grid">
      <ol class="products list items product-items">
<?php
$result1 = $connection->fetchAll("SELECT distinct art_cat FROM art_table WHERE art_user =". $artist);
foreach ($result1 as $key){
  $cat_id = $key['art_cat'];
  $product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id);
  $cat_img =  $product->getData('thumbnail');
  $price = $product->getPrice();
  $formattedPrice = $priceHelper->currency($price, true, false);
    ?>
    <li class="item product product-item">
        <div class="product-item-info" data-container="product-grid">
          <a class="product photo product-item-photo" href="<?php echo $product->getProductUrl();?>" tabindex="-1">
            <span class="product-image-container" style="width:240px;">
              <span class="product-image-wrapper" style="padding-bottom: 125%;">
                <img class="product-image-photo" src="<?php echo $media_url."catalog/product".$cat_img;?>" alt="<?php echo $product->getName();?>" width="240" height="300">
              </span>
            </span>
          </a>
          <div class="product details product-item-details">
              <strong class="product name product-item-name">
                <a class="product-item-link" href="<?php echo $product->getProductUrl();?>"> <?php echo $product->getName();?> </a>
              </strong>
              <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $cat_id;?>">
                <span class="price-container price-final_price tax weee">
                  <span id="product-price-6" class="price-wrapper " data-price-amount="<?php echo $price;?>" data-price-type="finalPrice">
                    <span class="price"><?php echo $formattedPrice;?></span>
                  </span>
                </span>
              </div>
          </div>
        </div>
    </li>
    <?php
}
?>
      </ol>
  </div>
