<?php
/** @var $helper \Mageplaza\Productslider\Helper\Data */
$helper = $this->helper('Mageplaza\Productslider\Helper\Data');
?>
<?php if ($helper->isEnabled()): ?>

    <?php if (true || ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize()))): ?>
        <?php
        $type = 'widget-product-grid';
        $mode = 'grid';
        $productsliderId = $block->getUniqueSliderKey();
        $image = 'new_products_content_widget_grid';

//  $items = $block->getProductCollection()->getItems();
        $title = $block->getConfigValue('heading');
        $info = $block->getConfigValue('description');

        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
        $description = false;
        ?>

        <div class="mp-product-slider-block block widget block-products-list <?php echo $mode; ?>">
            <?php if ($title): ?>
                <h2 class="mp-product-slider-title"><?php echo $title; ?></h2>
            <?php endif ?>
        </div>

        <p class="mp-ps-info"><?php echo $info; ?></p>
        <div class="block-content slider-content">
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items <?php echo $type; ?>">
                    <?php //$iterator = 1;  ?>
                    <div class="owl-carousel" id="mageplaza-product-slider-<?php echo $productsliderId; ?>">
                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $blockObj = $block->getLayout()->createBlock('Artist\Artwork\Block\User');
                        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                        $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                        if ($customerSession->isLoggedIn()) {
                            $cid = $customerSession->getCustomer()->getId();
                        }

                        $art_prof_pic = "";
                        $pslogin = $storeManager->getStore()->getBaseUrl() . "pub/media/pslogin/photo/";
                        $bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
                        $png = '.png';
                        $stat_prof_img = $storeManager->getStore()->getBaseUrl();
                        $connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');

//                        if (isset($cid)) {
//                            $result = $connection->fetchAll("SELECT *,GROUP_CONCAT(art_title) as art_titles FROM art_table WHERE art_who=1 AND art_title IS NOT NULL GROUP BY art_user");
//                        } else {
//                            $result = $connection->fetchAll("SELECT *,GROUP_CONCAT(art_title) as art_titles FROM art_table WHERE art_who=1 AND art_title IS NOT NULL GROUP BY art_user");
//                        }
                        $result = $connection->fetchAll("SELECT * FROM artist_list WHERE featured_status=1");

                        foreach ($result as $key) {
                            $entity_id = $key['artist_id'];
                            if ($entity_id != '') {
                                $result1 = $connection->fetchAll("SELECT * FROM plumrocket_sociallogin_account WHERE customer_id=" . $entity_id);
                                $count = count($result1);
                                try {
                                    $customer_obj = $objectManager->get('Magento\Customer\Model\Customer')->load($entity_id);
                                    $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
                                    $cust_details = $customerRepository->getById($entity_id);
                                } catch (Exception $e) {
                                    continue;
                                }
                                //echo "Image->".$cust_details->getCustomAttribute('prof_image');die;
                                if ($count > 0) {
                                    if ($cust_details->getCustomAttribute('prof_image')) {
                                        $art_prof_pic = $cust_details->getCustomAttribute('prof_image')->getValue();
                                        $artist_pic = $bu . $art_prof_pic;
                                    } else {
                                        $fb_user = $result1[0]['customer_id'];
                                        $artist_pic = $pslogin . $fb_user . $png;
                                    }
                                } else {
                                    if ($cust_details->getCustomAttribute('prof_image')) {
                                        $art_prof_pic = $cust_details->getCustomAttribute('prof_image')->getValue();
                                        $artist_pic = $bu . $art_prof_pic;
                                    } else {
                                        $artist_pic = $stat_prof_img . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
                                    }
                                }
                                $follower_first_name = $customer_obj->getData('firstname');
                                $follower_last_name = $customer_obj->getData('lastname');
                                $follower_name = $follower_first_name . " " . $follower_last_name;
                                ?>

                                <div class="artist_details">	
                                    <div class="artist_pic">
                                        <img src="<?php echo $artist_pic; ?>" alt="" class="canvas-export" width="40" height="40">
                                    </div>
                                    <div class="artists">
                                        <a href="<?php
                                        echo $blockObj->getUserUrl($entity_id)
//echo $stat_prof_img.'artwork/account/user/'.'?='.$art_user;       
                                        ?>"><?php echo $follower_name; ?></a> 
                                    </div>
                                </div>            
                                <?php
                            }
                        }
                        //echo "Work-".$productsliderId;die;
                        ?>       
                    </div>
                </ol>
            </div>
        </div>
        <script>
            require([
                'jquery',
                'Mageplaza_Productslider/js/owl.carousel.min'
            ], function ($) {
                $('#mageplaza-product-slider-<?php echo $productsliderId; ?>').owlCarousel(<?php echo ($block->getAllOptions()) ?>);
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
