<?php
$helper = $this->helper('Mageplaza\Productslider\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$media_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseURL = $storeManager->getStore()->getBaseUrl();
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');

$registry = $objectManager->get("Magento\Framework\Registry");
$currentProduct = $registry->registry('product');
if ($currentProduct->getId()) {
    $userid = $currentProduct->getData("yourcustomattribute_id");
    $currentProductID = $currentProduct->getId();

    $result = $connection->fetchAll("SELECT * FROM art_enable_prouct INNER JOIN art_table ON art_table.art_id = art_enable_prouct.art_id WHERE art_enable_prouct.art_status=1 AND art_table.art_cat=art_enable_prouct.art_product AND art_table.art_who=1 AND art_table.art_user=" . $userid ." AND art_enable_prouct.art_product !=".$currentProductID);
} else {
    $result = $connection->fetchAll("SELECT * FROM art_enable_prouct INNER JOIN art_table ON art_table.art_id = art_enable_prouct.art_id WHERE art_enable_prouct.art_status=1 AND art_table.art_cat=art_enable_prouct.art_product AND art_table.art_who=1");
}
/** @var $helper \Mageplaza\Productslider\Helper\Data */
$helper = $this->helper('Mageplaza\Productslider\Helper\Data');
?>
<?php if ($helper->isEnabled()): ?>


    <?php
    /**
     * Template for displaying products list widget
     *
     * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
     */
    ?>
    <?php if (true || ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize()))): ?>
        <?php
        $type = 'widget-product-grid';
        $mode = 'grid';
        $productsliderId = $block->getUniqueSliderKey();
        $image = 'new_products_content_widget_grid';

        $items = $block->getProductCollection()->getItems();
        $title = $block->getConfigValue('heading');
        $info = $block->getConfigValue('description');

        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
        $description = false;
        ?>


        <div class="mp-product-slider-block block widget block-products-list <?php echo $mode; ?>">
            <?php if ($title): ?>
                <h2 class="mp-product-slider-title"><?php echo $title; ?></h2>
            </div>
        <?php endif ?>

        <p class="mp-ps-info"><?php echo $info; ?></p>

        <div class="block-content">
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items <?php echo $type; ?>">
                    <?php //$iterator = 1;  ?>
                    <div class="owl-carousel" id="mageplaza-product-slider-<?php echo $productsliderId; ?>">
                        <?php
                        $username = "";
                        $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                        ?>
                        <?php
                        foreach ($result as $key) {
                            $cat_id = $key['art_cat'];
                            $art_user = $key['art_user'];
                            $product = $objectManager->get('Magento\Catalog\Model\Product')->load($cat_id);
                            $cat_img = $product->getData('thumbnail');
                            $price = $product->getPrice();
                            $formattedPrice = $priceHelper->currency($price, true, false);
                            $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
                            $cust_details = $customerRepository->getById($art_user);
                            if ($cust_details->getCustomAttribute('uname')) {
                                $username = $cust_details->getCustomAttribute('uname')->getValue();
                            }
                            ?>

                            <?php //echo ($iterator++ == 1) ? '<li class="product-item product-slider">' : '</li><li class="product-item product-slider">'     ?>


                            <div class="col-lg-4 product-div" style="width: 250px;float: left;margin: 10px;position: relative;">
                                <div class="slide-overlay" style="border: 2px solid gray;height: 300px;width: 240;">
                                    <a href="<?php echo $baseURL.$product->getData("url_key"); ?>">
                                        <img src="<?php echo $media_url . "catalog/product" . $cat_img; ?>"  style="height: 100%;width: 100%" alt="<?php echo $product->getName(); ?>">
                                    </a>
                                </div>
                                <div class="art-block">
                                    <div class="title-tag-price">
                                        <strong><?php echo $key['art_title']; ?></strong>&nbsp;&nbsp;<strong><?php echo $formattedPrice; ?></strong>
                                    </div>
                                    <div class="name-edit">
                                        <span class="cust_name">by <?php echo $username; ?></span>
                                    </div>
                                </div>
                            </div>

                        <?php } ?>
                        <?php //endforeach    ?>
                    </div>
                </ol>
            </div>

        </div>

        <script>
            require([
                'jquery',
                'Mageplaza_Productslider/js/owl.carousel.min'
            ], function ($) {
                var carouselOptions = <?php echo ($block->getAllOptions()) ?>;
                if ($('#mageplaza-product-slider-<?php echo $productsliderId; ?> .product-div').length <= 1) {
                    carouselOptions.dots = false;
                    carouselOptions.loop = false;
                }
                $('#mageplaza-product-slider-<?php echo $productsliderId; ?>').owlCarousel();
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
