<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
try {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $base_url = $storeManager->getStore()->getBaseUrl();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
    $cid = 0;
    if ($customerSession->isLoggedIn()) {
        $cid = $customerSession->getCustomer()->getId();
    }
    $_productId = $block->getProduct()->getId();
    $currentProduct = $objectManager->get('Magento\Catalog\Model\Product')->load($_productId);
    $userid = $currentProduct->getData("yourcustomattribute_id");
    $connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
    $wish = "false";
    $wish_result = array();
    if ($cid) {
        $wish_result = $connection->fetchAll("SELECT * FROM wishlist INNER JOIN wishlist_item ON wishlist.wishlist_id = wishlist_item.wishlist_id WHERE wishlist.customer_id=" . $cid . " AND wishlist_item.product_id=" . $_productId);
        if (count($wish_result) > 0) {
            $wish = "true";
        } else {
            $wish = "false";
        }
    }
    ?>
    <?php if ($block->isWishListAllowed()) : ?>        
        <?php
        if (count($wish_result)) {
            ?>
            <form name="wishlist-remove-form" action="<?php echo $base_url; ?>wishlist/index/remove" method="post">
                <input type="hidden" name="item" value="<?php
                echo $wish_result[0]['wishlist_item_id'];
                ?>" />
            </form>
        <?php } ?>
        <a href="#"
           class="action towishlist 123 <?php
           if ($wish == 'true') {
               echo 'red';
           }
           ?>"
           <?php if (!count($wish_result)) { ?>
               data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>'
               data-action="add-to-wishlist"
           <?php } ?>
           <?php
           if ($customerSession->isLoggedIn()) {
               if (count($wish_result)) {
                   ?>onclick="return removeItem()"<?php
               }
           } else {
               ?>
               onclick="return altmsg()"
           <?php } ?>><span><?php /* @escapeNotVerified */ echo __('') ?></span></a>
       <?php endif; ?>
    <script type="text/x-magento-init">
        {
        "body": {
        "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
        }
        }
    </script>
    <script type="text/javascript">
        function altmsg()
        {
            alert("Please login first or create an account if you want to mark any product as favourite.");
            return false;
        }

        function removeItem() {
            jQuery("form[name=wishlist-remove-form]").submit();
        }
    </script>
    <?php
} catch (Exception $e) {
    echo $e->getMessage();
}
?>
