<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$bu = $storeManager->getStore()->getBaseUrl() . "pub/media/customer";
$watermark = $storeManager->getStore()->getBaseUrl() . "pub/media/watermark/";
$stat_watermark = $storeManager->getStore()->getBaseUrl() . "pub/static/frontend/Custom/theme/en_US/images/edit-profile.png";
$right_click = "";
$upload_watermark = "";
$watermark_image = "";
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {
    $cid = $customerSession->getCustomer()->getId();
}

$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
$table = $connection->getTableName('image_settings');

$result1 = $connection->fetchAll("SELECT * FROM image_settings WHERE artist_id =" . $cid);
$watermarkExists = false;

foreach ($result1 as $key) {
    $watermarkExists = true;
    $watermark_image = $key['watermark_image'];
    ?>
    <input type = "hidden" id ="wat_img" name="wat_img" value ="<?php echo $watermark_image; ?>" >
    <?php
    //$id = $key['id'];
}

if ($block->getCustomer()->getCustomAttribute('right_click')) {
    $right_click = $block->getCustomer()->getCustomAttribute('right_click')->getValue();
}

if ($block->getCustomer()->getCustomAttribute('upload_watermark')) {
    $upload_watermark = $block->getCustomer()->getCustomAttribute('upload_watermark')->getValue();
}
?>
<div class="container">
    <form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('settings/account/save') ?>" method="post" id="" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
        <fieldset class="fieldset info">
            <?php echo $block->getBlockHtml('formkey') ?>
            <div class="image-settings">
                <strong role="heading" aria-level="2"><span><?php echo __('Download protection') ?></span></strong>
                <div class="control">
                    <span class="checkbox">
                        <label for="right_click">
                            <input type="checkbox" id="right_click" name="right_click" class="checkbox" value="1" <?php
                            if ($right_click)
                                echo 'checked';
                            else
                                echo ''
                                ?> >
                            <p>Discourage people from right-clicking or saving my images by placing a transparent image over the top of them.</p>
                        </label>
                        <div class="note">
                            Please understand its impossible to prevent downloading of images displayed on web pages, but activating this feature will make it more difficult. Your original high-resolution images are never displayed on the website, and cannot be downloaded.
                        </div>
                    </span>
                </div>
                <div></div><br />
                <input type="hidden" name="attr_id" value="177">
                <input type="hidden" name="value_id" value="<?php //if($id) echo $id; else echo '';          ?>">
                <strong role="heading" aria-level="2"><span><?php echo __('Zoom View Watermark') ?></span></strong>
                <div class="control">
                    <span class="checkbox">
                        <label for="upload_watermark">
                            <input type="checkbox" id="upload_watermark" name="upload_watermark" class="checkbox" value="1" <?php
                            if ($watermarkExists)
                                echo 'checked';
                            else
                                echo ''
                                ?> ><p>Place a large watermark in the center of my images</p>
                        </label>
                    </span>
                </div>

                <div class="field watermark_image required" id="watermark-image-container" data-container="change-watermark_image" style="<?php if (!$watermarkExists) echo 'display:none'; ?>">
                    <label class="label" for="watermark_image"><span><?php /* @escapeNotVerified */ echo __('Watermark Image') ?></span></label>
                    <div class="control">
                        <div class="watermark_center">
                            <input type="file" accept="image/png" name="watermark_image" id="watermark_image" onchange="watermark(this);">
                            <p>Recommended watermark image dimensions 300 * 100 (w*h)</p>

                            <img src="<?php
                            if ($watermark_image)
                                echo $watermark . $watermark_image;
                            else
                                echo $stat_watermark;
                            ?>" id="watermark_img" alt="" width="40%" height="40%" style="<?php
                                 if (!$watermarkExists) {
                                     echo 'display:none';
                                 }
                                 ?>">
                        </div>
                    </div>
                </div>
            </div>

            <!--<div class="field watermark_image required" data-container="change-watermark_image">
              <label class="label" for="watermark_image"><span><?php /* @escapeNotVerified */ echo __('Watermark Image') ?></span></label>
                <div class="control">
                    <div class="watermark_center">
                        <input type="file" name="watermark_image" id="watermark_image" onchange="watermark(this);">
                        <!--<img src="<?php //if($watermark_img) echo $bu.$watermark_img; else echo $stat_watermark;        ?>" id="watermark_img" alt="" width="20%" height="20%">
                    </div>
                 </div>
            </div>-->

            <?php //echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
            <div class="field choice" style="display:none;">
                <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" class="checkbox" />
                <label class="label" for="change-email"><span><?php /* @escapeNotVerified */ echo __('Change Email') ?></span></label>
            </div>
            <div class="field choice" style="display:none;">
                <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
            </div>

        </fieldset>

        <fieldset class="fieldset password" data-container="change-email-password">
            <legend class="legend"><span data-title="change-email-password"><?php /* @escapeNotVerified */ echo __('Change Email and Password') ?></span></legend><br>
            <div class="field email required" data-container="change-email">
                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
                </div>
            </div>
            <div class="field password current required">
                <label class="label" for="current-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
                </div>
            </div>
            <div class="field new password required" data-container="new-password" data-mage-init=' {
                 "passwordStrengthIndicator": {

                 }
                 }'>
                <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off" />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" >
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirm password required" data-container="confirm-password">
                <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                           data-input="confirm-password"
                           autocomplete="off" />
                </div>
            </div>
            <?php echo $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save1') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
            </div>
        </div>
    </form>
</div>

<script>
    require([
            "jquery",
            "mage/mage"
    ], function($){
    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
            ?>;
    dataForm.mage('validation', {
<?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
        if (element.prop('id').search('full') !== - 1) {
        var dobElement = $(element).parents('.customer-dob'),
                errorClass = error.prop('class');
        error.insertAfter(element.parent());
        dobElement.find('.validate-custom').addClass(errorClass)
                .after('<div class="' + errorClass + '"></div>');
        }
        else {
        error.insertAfter(element);
        }
        },
                ignore: ':hidden:not(' + ignore + ')'
<?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
<?php endif ?>
    });
    });</script>
<script type="text/x-magento-init">
    {
    "[data-role=change-email], [data-role=change-password]": {
    "changeEmailPassword": {
    "titleChangeEmail": "<?php /* @escapeNotVerified */ echo __('Change Email') ?>",
    "titleChangePassword": "<?php /* @escapeNotVerified */ echo __('Change Password') ?>",
    "titleChangeEmailAndPassword": "<?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>"
    }
    }
    }
</script>

<script>


    require(['jquery', 'jquery/ui', 'jquery/validate'], function ($) {
    $(document).ready(function ($) {

    //    $('#watermark_image').hide();
    //    if ($('#upload_watermark').is(':checked')) {
    //    $('#watermark_image').show();
    //    }
    $('#upload_watermark').change(function () {
    $('#watermark-image-container').toggle();
    /*if ($(this).is(':checked')) {
     $('#watermark_image').show();
     }*/

    });
    // $("#form-validate").validate({
    //   rules: {
    //     right_click:"required",
    //     upload_watermark:"required",
    //   },
    //   messages:{
    //     right_click:{
    //       required:"Please select the check box to proceed.",
    //     },
    //     upload_watermark:{
    //       required:"Please select the check box to proceed.",
    //     },
    //   }
    // });
    });
    });
</script>

