<?php
/**
 *
 * */
?>
<?php if ($post = $this->getPost()): ?>
    <div class="post-user post-meta-item"><strong><?php echo __('Posted By') ?>:</strong> <a href="<?php echo $post->getUser()->getUrl() ?>"><?php echo $post->getUser()->getDisplayName() ?></a></div>
    <div class="post-header clearfix">
        <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $post->getUrl() ?>">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_pinterest"></a>
            <!--<a class="addthis_button_email"></a>-->
            <!--<a class="addthis_button_compact"></a>-->
        </div> 
    </div>
    <script type="text/javascript">var addthis_config = {"data_track_clickback": false};</script>
    <!--<script type="text/javascript" async src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4def63cd3cf37569"></script> -->
    <script type="text/javascript">
        var addthis_config = {
            ui_language: "en"
        }
        addthis_config.ui_email_from = 'technourcedrive@gmail.com';
    </script>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
<!--<div class="addthis_inline_share_toolbox"></div>-->

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-595a3a14ec394cf8"></script>

<?php endif; ?>